package bean;
// Generated 16/09/2023 21:10:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClientePbt generated by hbm2java
 */
@Entity
@Table(name="cliente_pbt"
    ,catalog="sistema4"
)
public class ClientePbt  implements java.io.Serializable {


     private int idClientePbt;
     private String nomePbt;
     private String emailPbt;
     private String cpfPbt;
     private String cepPbt;
     private String telefonePbt;
     private String rgPbt;
     private String dadospagamentoPbt;
     private String datanascimentoPbt;
     private String sexoPbt;
     private String cidadePbt;
     private String barroPbt;
     private String celularPbt;
     private String paisPbt;
     private String apelidoPbt;

    public ClientePbt() {
    }

    public ClientePbt(int idClientePbt, String nomePbt, String emailPbt, String cpfPbt, String cepPbt, String telefonePbt, String rgPbt, String dadospagamentoPbt, String datanascimentoPbt, String sexoPbt, String cidadePbt, String barroPbt, String celularPbt, String paisPbt, String apelidoPbt) {
       this.idClientePbt = idClientePbt;
       this.nomePbt = nomePbt;
       this.emailPbt = emailPbt;
       this.cpfPbt = cpfPbt;
       this.cepPbt = cepPbt;
       this.telefonePbt = telefonePbt;
       this.rgPbt = rgPbt;
       this.dadospagamentoPbt = dadospagamentoPbt;
       this.datanascimentoPbt = datanascimentoPbt;
       this.sexoPbt = sexoPbt;
       this.cidadePbt = cidadePbt;
       this.barroPbt = barroPbt;
       this.celularPbt = celularPbt;
       this.paisPbt = paisPbt;
       this.apelidoPbt = apelidoPbt;
    }
   
     @Id 

    
    @Column(name="id cliente_pbt", unique=true, nullable=false)
    public int getIdClientePbt() {
        return this.idClientePbt;
    }
    
    public void setIdClientePbt(int idClientePbt) {
        this.idClientePbt = idClientePbt;
    }

    
    @Column(name="nome_pbt", nullable=false, length=45)
    public String getNomePbt() {
        return this.nomePbt;
    }
    
    public void setNomePbt(String nomePbt) {
        this.nomePbt = nomePbt;
    }

    
    @Column(name="email_pbt", nullable=false, length=45)
    public String getEmailPbt() {
        return this.emailPbt;
    }
    
    public void setEmailPbt(String emailPbt) {
        this.emailPbt = emailPbt;
    }

    
    @Column(name="cpf_pbt", nullable=false, length=45)
    public String getCpfPbt() {
        return this.cpfPbt;
    }
    
    public void setCpfPbt(String cpfPbt) {
        this.cpfPbt = cpfPbt;
    }

    
    @Column(name="cep_pbt", nullable=false, length=45)
    public String getCepPbt() {
        return this.cepPbt;
    }
    
    public void setCepPbt(String cepPbt) {
        this.cepPbt = cepPbt;
    }

    
    @Column(name="telefone_pbt", nullable=false, length=45)
    public String getTelefonePbt() {
        return this.telefonePbt;
    }
    
    public void setTelefonePbt(String telefonePbt) {
        this.telefonePbt = telefonePbt;
    }

    
    @Column(name="rg_pbt", nullable=false, length=45)
    public String getRgPbt() {
        return this.rgPbt;
    }
    
    public void setRgPbt(String rgPbt) {
        this.rgPbt = rgPbt;
    }

    
    @Column(name="dadospagamento__pbt", nullable=false, length=45)
    public String getDadospagamentoPbt() {
        return this.dadospagamentoPbt;
    }
    
    public void setDadospagamentoPbt(String dadospagamentoPbt) {
        this.dadospagamentoPbt = dadospagamentoPbt;
    }

    
    @Column(name="datanascimento_pbt", nullable=false, length=45)
    public String getDatanascimentoPbt() {
        return this.datanascimentoPbt;
    }
    
    public void setDatanascimentoPbt(String datanascimentoPbt) {
        this.datanascimentoPbt = datanascimentoPbt;
    }

    
    @Column(name="sexo_pbt", nullable=false, length=45)
    public String getSexoPbt() {
        return this.sexoPbt;
    }
    
    public void setSexoPbt(String sexoPbt) {
        this.sexoPbt = sexoPbt;
    }

    
    @Column(name="cidade_pbt", nullable=false, length=45)
    public String getCidadePbt() {
        return this.cidadePbt;
    }
    
    public void setCidadePbt(String cidadePbt) {
        this.cidadePbt = cidadePbt;
    }

    
    @Column(name="barro_pbt", nullable=false, length=45)
    public String getBarroPbt() {
        return this.barroPbt;
    }
    
    public void setBarroPbt(String barroPbt) {
        this.barroPbt = barroPbt;
    }

    
    @Column(name="celular_pbt", nullable=false, length=45)
    public String getCelularPbt() {
        return this.celularPbt;
    }
    
    public void setCelularPbt(String celularPbt) {
        this.celularPbt = celularPbt;
    }

    
    @Column(name="pais_pbt", nullable=false, length=45)
    public String getPaisPbt() {
        return this.paisPbt;
    }
    
    public void setPaisPbt(String paisPbt) {
        this.paisPbt = paisPbt;
    }

    
    @Column(name="apelido_pbt", nullable=false, length=45)
    public String getApelidoPbt() {
        return this.apelidoPbt;
    }
    
    public void setApelidoPbt(String apelidoPbt) {
        this.apelidoPbt = apelidoPbt;
    }




}


