package bean;
// Generated 16/09/2023 21:10:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FuncionarioPbt generated by hbm2java
 */
@Entity
@Table(name="funcionario_pbt"
    ,catalog="sistema4"
)
public class FuncionarioPbt  implements java.io.Serializable {


     private int idfuncionarioPbt;
     private String nome;
     private String email;
     private String telefone;
     private String cpf;

    public FuncionarioPbt() {
    }

    public FuncionarioPbt(int idfuncionarioPbt, String nome, String email, String telefone, String cpf) {
       this.idfuncionarioPbt = idfuncionarioPbt;
       this.nome = nome;
       this.email = email;
       this.telefone = telefone;
       this.cpf = cpf;
    }
   
     @Id 

    
    @Column(name="idfuncionario_pbt", unique=true, nullable=false)
    public int getIdfuncionarioPbt() {
        return this.idfuncionarioPbt;
    }
    
    public void setIdfuncionarioPbt(int idfuncionarioPbt) {
        this.idfuncionarioPbt = idfuncionarioPbt;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefone", nullable=false, length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="cpf", nullable=false, length=45)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }




}


