package bean;
// Generated 16/09/2023 21:10:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoPbt generated by hbm2java
 */
@Entity
@Table(name="produto_pbt"
    ,catalog="sistema4"
)
public class ProdutoPbt  implements java.io.Serializable {


     private int idprodutoPbt;
     private String nomePbt;
     private String descricaoPbt;
     private String valorPbt;
     private String categoriaPbt;
     private Set vendaProdutoPbts = new HashSet(0);

    public ProdutoPbt() {
    }

	
    public ProdutoPbt(int idprodutoPbt, String nomePbt, String descricaoPbt, String valorPbt, String categoriaPbt) {
        this.idprodutoPbt = idprodutoPbt;
        this.nomePbt = nomePbt;
        this.descricaoPbt = descricaoPbt;
        this.valorPbt = valorPbt;
        this.categoriaPbt = categoriaPbt;
    }
    public ProdutoPbt(int idprodutoPbt, String nomePbt, String descricaoPbt, String valorPbt, String categoriaPbt, Set vendaProdutoPbts) {
       this.idprodutoPbt = idprodutoPbt;
       this.nomePbt = nomePbt;
       this.descricaoPbt = descricaoPbt;
       this.valorPbt = valorPbt;
       this.categoriaPbt = categoriaPbt;
       this.vendaProdutoPbts = vendaProdutoPbts;
    }
   
     @Id 

    
    @Column(name="idproduto_pbt", unique=true, nullable=false)
    public int getIdprodutoPbt() {
        return this.idprodutoPbt;
    }
    
    public void setIdprodutoPbt(int idprodutoPbt) {
        this.idprodutoPbt = idprodutoPbt;
    }

    
    @Column(name="nome_pbt", nullable=false, length=45)
    public String getNomePbt() {
        return this.nomePbt;
    }
    
    public void setNomePbt(String nomePbt) {
        this.nomePbt = nomePbt;
    }

    
    @Column(name="descricao_pbt", nullable=false, length=45)
    public String getDescricaoPbt() {
        return this.descricaoPbt;
    }
    
    public void setDescricaoPbt(String descricaoPbt) {
        this.descricaoPbt = descricaoPbt;
    }

    
    @Column(name="valor_pbt", nullable=false, length=45)
    public String getValorPbt() {
        return this.valorPbt;
    }
    
    public void setValorPbt(String valorPbt) {
        this.valorPbt = valorPbt;
    }

    
    @Column(name="categoria_pbt", nullable=false, length=45)
    public String getCategoriaPbt() {
        return this.categoriaPbt;
    }
    
    public void setCategoriaPbt(String categoriaPbt) {
        this.categoriaPbt = categoriaPbt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produtoPbt")
    public Set getVendaProdutoPbts() {
        return this.vendaProdutoPbts;
    }
    
    public void setVendaProdutoPbts(Set vendaProdutoPbts) {
        this.vendaProdutoPbts = vendaProdutoPbts;
    }




}


