package bean;
// Generated 16/09/2023 21:10:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UsuarioPbt generated by hbm2java
 */
@Entity
@Table(name="usuario_pbt"
    ,catalog="sistema4"
)
public class UsuarioPbt  implements java.io.Serializable {


     private int idusuarioPbt;
     private String nomePbt;
     private String nicknamePbt;
     private String cpfPbt;
     private String dataNascimentoPbt;
     private String senhaPbt;
     private String nivelPbt;
     private String ativoPbt;

    public UsuarioPbt() {
    }

    public UsuarioPbt(int idusuarioPbt, String nomePbt, String nicknamePbt, String cpfPbt, String dataNascimentoPbt, String senhaPbt, String nivelPbt, String ativoPbt) {
       this.idusuarioPbt = idusuarioPbt;
       this.nomePbt = nomePbt;
       this.nicknamePbt = nicknamePbt;
       this.cpfPbt = cpfPbt;
       this.dataNascimentoPbt = dataNascimentoPbt;
       this.senhaPbt = senhaPbt;
       this.nivelPbt = nivelPbt;
       this.ativoPbt = ativoPbt;
    }
   
     @Id 

    
    @Column(name="idusuario_pbt", unique=true, nullable=false)
    public int getIdusuarioPbt() {
        return this.idusuarioPbt;
    }
    
    public void setIdusuarioPbt(int idusuarioPbt) {
        this.idusuarioPbt = idusuarioPbt;
    }

    
    @Column(name="nome_pbt", nullable=false, length=45)
    public String getNomePbt() {
        return this.nomePbt;
    }
    
    public void setNomePbt(String nomePbt) {
        this.nomePbt = nomePbt;
    }

    
    @Column(name="nickname_pbt", nullable=false, length=45)
    public String getNicknamePbt() {
        return this.nicknamePbt;
    }
    
    public void setNicknamePbt(String nicknamePbt) {
        this.nicknamePbt = nicknamePbt;
    }

    
    @Column(name="cpf_pbt", nullable=false, length=45)
    public String getCpfPbt() {
        return this.cpfPbt;
    }
    
    public void setCpfPbt(String cpfPbt) {
        this.cpfPbt = cpfPbt;
    }

    
    @Column(name="dataNascimento_pbt", nullable=false, length=45)
    public String getDataNascimentoPbt() {
        return this.dataNascimentoPbt;
    }
    
    public void setDataNascimentoPbt(String dataNascimentoPbt) {
        this.dataNascimentoPbt = dataNascimentoPbt;
    }

    
    @Column(name="senha_pbt", nullable=false, length=45)
    public String getSenhaPbt() {
        return this.senhaPbt;
    }
    
    public void setSenhaPbt(String senhaPbt) {
        this.senhaPbt = senhaPbt;
    }

    
    @Column(name="nivel_pbt", nullable=false, length=45)
    public String getNivelPbt() {
        return this.nivelPbt;
    }
    
    public void setNivelPbt(String nivelPbt) {
        this.nivelPbt = nivelPbt;
    }

    
    @Column(name="ativo_pbt", nullable=false, length=45)
    public String getAtivoPbt() {
        return this.ativoPbt;
    }
    
    public void setAtivoPbt(String ativoPbt) {
        this.ativoPbt = ativoPbt;
    }




}


