package bean;
// Generated 16/09/2023 21:10:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VendaPbt generated by hbm2java
 */
@Entity
@Table(name="venda_pbt"
    ,catalog="sistema4"
)
public class VendaPbt  implements java.io.Serializable {


     private int idvendaPbt;
     private String dataPbt;
     private String totalPbt;
     private String formapagamentoPbt;
     private String statusvendaPbt;
     private Set vendaProdutoPbts = new HashSet(0);

    public VendaPbt() {
    }

	
    public VendaPbt(int idvendaPbt, String dataPbt, String totalPbt, String formapagamentoPbt, String statusvendaPbt) {
        this.idvendaPbt = idvendaPbt;
        this.dataPbt = dataPbt;
        this.totalPbt = totalPbt;
        this.formapagamentoPbt = formapagamentoPbt;
        this.statusvendaPbt = statusvendaPbt;
    }
    public VendaPbt(int idvendaPbt, String dataPbt, String totalPbt, String formapagamentoPbt, String statusvendaPbt, Set vendaProdutoPbts) {
       this.idvendaPbt = idvendaPbt;
       this.dataPbt = dataPbt;
       this.totalPbt = totalPbt;
       this.formapagamentoPbt = formapagamentoPbt;
       this.statusvendaPbt = statusvendaPbt;
       this.vendaProdutoPbts = vendaProdutoPbts;
    }
   
     @Id 

    
    @Column(name="idvenda_pbt", unique=true, nullable=false)
    public int getIdvendaPbt() {
        return this.idvendaPbt;
    }
    
    public void setIdvendaPbt(int idvendaPbt) {
        this.idvendaPbt = idvendaPbt;
    }

    
    @Column(name="data_pbt", nullable=false, length=45)
    public String getDataPbt() {
        return this.dataPbt;
    }
    
    public void setDataPbt(String dataPbt) {
        this.dataPbt = dataPbt;
    }

    
    @Column(name="total_pbt", nullable=false, length=45)
    public String getTotalPbt() {
        return this.totalPbt;
    }
    
    public void setTotalPbt(String totalPbt) {
        this.totalPbt = totalPbt;
    }

    
    @Column(name="formapagamento_pbt", nullable=false, length=45)
    public String getFormapagamentoPbt() {
        return this.formapagamentoPbt;
    }
    
    public void setFormapagamentoPbt(String formapagamentoPbt) {
        this.formapagamentoPbt = formapagamentoPbt;
    }

    
    @Column(name="statusvenda_pbt", nullable=false, length=45)
    public String getStatusvendaPbt() {
        return this.statusvendaPbt;
    }
    
    public void setStatusvendaPbt(String statusvendaPbt) {
        this.statusvendaPbt = statusvendaPbt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendaPbt")
    public Set getVendaProdutoPbts() {
        return this.vendaProdutoPbts;
    }
    
    public void setVendaProdutoPbts(Set vendaProdutoPbts) {
        this.vendaProdutoPbts = vendaProdutoPbts;
    }




}


