package bean;
// Generated 16/09/2023 21:10:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaProdutoPbt generated by hbm2java
 */
@Entity
@Table(name="venda_produto_pbt"
    ,catalog="sistema4"
)
public class VendaProdutoPbt  implements java.io.Serializable {


     private int idvendaProdutoPbt;
     private ProdutoPbt produtoPbt;
     private VendaPbt vendaPbt;
     private double valorunitarioPbt;
     private double quantidadePbt;

    public VendaProdutoPbt() {
    }

    public VendaProdutoPbt(int idvendaProdutoPbt, ProdutoPbt produtoPbt, VendaPbt vendaPbt, double valorunitarioPbt, double quantidadePbt) {
       this.idvendaProdutoPbt = idvendaProdutoPbt;
       this.produtoPbt = produtoPbt;
       this.vendaPbt = vendaPbt;
       this.valorunitarioPbt = valorunitarioPbt;
       this.quantidadePbt = quantidadePbt;
    }
   
     @Id 

    
    @Column(name="idvenda_produto_pbt", unique=true, nullable=false)
    public int getIdvendaProdutoPbt() {
        return this.idvendaProdutoPbt;
    }
    
    public void setIdvendaProdutoPbt(int idvendaProdutoPbt) {
        this.idvendaProdutoPbt = idvendaProdutoPbt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproduto_pbt", nullable=false)
    public ProdutoPbt getProdutoPbt() {
        return this.produtoPbt;
    }
    
    public void setProdutoPbt(ProdutoPbt produtoPbt) {
        this.produtoPbt = produtoPbt;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvenda_pbt", nullable=false)
    public VendaPbt getVendaPbt() {
        return this.vendaPbt;
    }
    
    public void setVendaPbt(VendaPbt vendaPbt) {
        this.vendaPbt = vendaPbt;
    }

    
    @Column(name="valorunitario_pbt", nullable=false, precision=22, scale=0)
    public double getValorunitarioPbt() {
        return this.valorunitarioPbt;
    }
    
    public void setValorunitarioPbt(double valorunitarioPbt) {
        this.valorunitarioPbt = valorunitarioPbt;
    }

    
    @Column(name="quantidade_pbt", nullable=false, precision=22, scale=0)
    public double getQuantidadePbt() {
        return this.quantidadePbt;
    }
    
    public void setQuantidadePbt(double quantidadePbt) {
        this.quantidadePbt = quantidadePbt;
    }




}


